import globalSliceReducer, {
  setSnackBar,
  resetSnackBar,
  setDialog,
  resetDialog,
  setLanguage,
  resetLanguage,
  initialState as globalInitialState,
  setActiveMenu,
  resetActiveMenu,
  setAuth,
  setOpenDrawer,
  closeDialog,
  setBrokerId,
  setUserProfile,
  setSasToken,
  setActivator,
  setTabIndex,
  setPromotionCode,
} from "./globalSlice";

export {
  // #region global slice
  globalInitialState,
  globalSliceReducer,
  setSnackBar,
  resetSnackBar,
  setDialog,
  resetDialog,
  setLanguage,
  resetLanguage,
  setActiveMenu,
  resetActiveMenu,
  setAuth,
  setOpenDrawer,
  closeDialog,
  setBrokerId,
  setUserProfile,
  setSasToken,
  setActivator,
  setTabIndex,
  setPromotionCode,
  // #endregion
};
